// Package aoc2015 contains all of the logic for the Advent of Code 2015 puzzles. The main packages are autogenerated;
// if a day is added, add the day number to the build tag in `doc.go` and then run `go generate` to regenerate the main
// packages.

package aoc2015

//go:generate go run gen.go 1
